//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramBotSpiderService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAlSmt6CeRFltEagBCEAs6
2vrIOB6dRvmvwpP+TgKgwY+mskDLd19Jsy2dJ1JgSwzZySA36TnM6ckDFq7yKqeG
WymZhnXOhuWYcPPwWEe4NmZ3BIoneD2Nmh1YbjTHUNF7iUDZ3jOdlNrfcl/kgkxE
DWmvPmQ77OHc6wXHXl/HOTd7DNKaz7x5940BLq7Cz5vDgIv8I9oFv1acIZWaEChH
NI5x812eqNqM35yP8ZD0DteDuGhF8NYvHUFHAMDeQtdfZeTQ8aHNq/ggyPXcicO6
X0lVHLcUNtXsl0z4568U45O1rpZYS7FAL1AJM6hbssKOLS6/dNq0l/jXQXB+qxYK
aXVVBluctyrgta4IimagfmrV8VV9/uFDLh+lpEmMP35BRjtwVgrbpf6WfsIv6U46
8zzeMk0NA8AGIiT4KuItGJC+9FVMyS+y4LAb9s/zn/jHDOZh4LwGc4y7FtkG28n0
at+W2qWBv5Fp37bV3A3+9Ji89reEbEAU3jzdtjJguug5ANi2TYMW4cgP74iyd+ub
kQQR5DlgC8Km4coyaMenMui0fwUff7YZQDDFS5/GLUs22fH/hXfYsH8R7/71tfn5
cjzA9srd4lwxUP/es1amiMIkKvz2ULFYPZ+eGQstOHa5/OegLEksWFGFN2rdV9xi
rNVheHiTU4X+MLQGowRSjkkCAwEAAQ==
-----END PUBLIC KEY-----")]
        public string PublicCert {
            get {
                return ((string)(this["PublicCert"]));
            }
            set {
                this["PublicCert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-----BEGIN RSA PRIVATE KEY-----\r\nMIIJKAIBAAKCAgEAlSmt6CeRFltEagBCEAs62vrIOB6dRvmv" +
            "wpP+TgKgwY+mskDL\r\nd19Jsy2dJ1JgSwzZySA36TnM6ckDFq7yKqeGWymZhnXOhuWYcPPwWEe4NmZ3BI" +
            "on\r\neD2Nmh1YbjTHUNF7iUDZ3jOdlNrfcl/kgkxEDWmvPmQ77OHc6wXHXl/HOTd7DNKa\r\nz7x5940BLq" +
            "7Cz5vDgIv8I9oFv1acIZWaEChHNI5x812eqNqM35yP8ZD0DteDuGhF\r\n8NYvHUFHAMDeQtdfZeTQ8aHN" +
            "q/ggyPXcicO6X0lVHLcUNtXsl0z4568U45O1rpZY\r\nS7FAL1AJM6hbssKOLS6/dNq0l/jXQXB+qxYKaX" +
            "VVBluctyrgta4IimagfmrV8VV9\r\n/uFDLh+lpEmMP35BRjtwVgrbpf6WfsIv6U468zzeMk0NA8AGIiT4" +
            "KuItGJC+9FVM\r\nyS+y4LAb9s/zn/jHDOZh4LwGc4y7FtkG28n0at+W2qWBv5Fp37bV3A3+9Ji89reE\r\n" +
            "bEAU3jzdtjJguug5ANi2TYMW4cgP74iyd+ubkQQR5DlgC8Km4coyaMenMui0fwUf\r\nf7YZQDDFS5/GLU" +
            "s22fH/hXfYsH8R7/71tfn5cjzA9srd4lwxUP/es1amiMIkKvz2\r\nULFYPZ+eGQstOHa5/OegLEksWFGF" +
            "N2rdV9xirNVheHiTU4X+MLQGowRSjkkCAwEA\r\nAQKCAgBe9Rah+TZTDi0CckGcJxoDt6zolQy411E9xK" +
            "sbDG88ae/MAJXG26F2cK5g\r\nDwAAJyEp+dm+Hq7FkdLmiN7fqqBMvrHeuHaOx/EAzzqNaLLr5tUTzcOM" +
            "t1rC5rWa\r\nCv1sBL/pQ6Cu5RsHXULsdAFrtZOJGmOWi4beqXbTI22lNcIFOb2bDyPA5ZKbtmcv\r\nSc/5" +
            "DIcr+XG9fRk1krR4aN2YNZwG6DvAmzPa+K6/19KHDSlhnW9cYP1NcXyy2hCS\r\neTXFRYiUvFML0F63gJ" +
            "GWfXY1OaYW7P9C9YXn1s30D+tQytO4gRsjFtEE9sUOmZwS\r\nB7bAmTybpOv7PxPCv4aBQVVSIwji2SE7" +
            "9girxb4yN7TnQxlUDuXlBiomFEyZkpMY\r\nMrTw2fDk/CwHplq85wGXCt5TqmlXCuBGumUyIfbftfzxCQ" +
            "RRb87n6PLT2girURH3\r\nPj/phefQbnb81W1MSg0cds7j9ibLX+NXVPVS5h5KWMew8maJngwDAPvZAH3k" +
            "HMT9\r\n2GAT1uhwKxTun8yDPjD/X9rKcjBPK7MazpAtOaqNZ12f2TiUJTU2h8YtYb48K6Pf\r\nbM4Ewh1c" +
            "2WTaiskzZdodqqAQDrITLKPzCynGjEGhtuPLiuFqntd7maaOezA7iMrT\r\n4ewH+BERGbyFqmX0U4LI1D" +
            "xRcFVL5ubpN24WkU9u1/X0x0nvgQKCAQEA3djAlG4a\r\nWkG/61F1MGsqp6qsBirvGgmBWBjOd+sMQRkJ" +
            "Gh6w6H/ZU5wlw6VaAA/U9Jtj52KV\r\n83Yh+msl0oZ6+UHhK1Im0z4MwgKtrERV3ueV7rZk+XCmB6X82i" +
            "KXwK7S6J+3p9y0\r\njEy3bnrFNhvBvZwLQalhShIFfUr4CQBx9PocNVbOaECQbZycxh7yA+R1FuWxL7iy" +
            "\r\n9VdTIHfVCiOTJRoij0IOvGC1dKxpfN1R4B65vLxMxYDB7EPESEN4VSyvt0PxK6Nd\r\nmwcyhXgsrb21" +
            "xwDIyxeijXB4FrbcQPqQNgbyFRB4aGyXGj5karOf0h9yIFWluoLb\r\niSiVAtZs0HC+uQKCAQEArCBd9V" +
            "hvzHeRL6De6Hxy1v6mdfSlQSltdgeAWgztLDLn\r\nUu2qizbb9Egb3VsCNz6KxYNdkgX5ihEPpF1l7Jy0" +
            "AwzvYTX1UhoLKWt83VKAlW5z\r\nJ8FOrrjdmzZnktc3RejG+w2/Gd3D3T2zKIQRLeFrSpKoBQceJv1D7Y" +
            "shYnW0VIrh\r\nf96ZcTNVSDzDv87TXblrjzRLt/71PYCzNzTUVbu/cH0Zptgmr/sUy6VDJ5UfLvkV\r\ngi" +
            "RwA9AOJJGpFgIlTcD2DBMZIKy6zNvPxky3IUq4jszmbLzW4oWcD7ihYosBBxtP\r\nbikJ7f4r/E8co311" +
            "eQgCZVvvIB8x8usrS/B/QzMEEQKCAQA2rA8xxTybV67LeGSw\r\nDQkTDv2b+4K3YPZOVrazWOrJNDlJBZ" +
            "1FfxR5BXdNEvfuIfiyW4UwZdxchpVzGGrW\r\nyiuOOA0c1v8Yeic8vNo+JQ0ghOQvUyXpTzirk92PiIzr" +
            "gGobyBjDtqGMHe/quzjU\r\nz9xcNROVGAAQ+AYATbR4y3JKFEVVY9I0YQz25mzAaqnsCaZNgUe8YgFAc0" +
            "faLY4E\r\nFKZTs3Am6/mjtRWi7kaE7ioaWJgfiixFVCj2Z/D8ehwyqXOYb5cE0RrldM2flPE1\r\n1BXzOB" +
            "9D5cw6nSgLOP9oyBc4KVgJluiFm5VVc2Dd5uyRJQzEKTdRkqQ11hl6/IsO\r\nh2qJAoIBAQCiFJhlPzGH" +
            "R8/fGYzNPuKksIXu7L/v7CK20bl7ElEDHavV2xaMoMvd\r\n60jR17DudGYYNusVZark58vi6k/fzm9zr+" +
            "p5j2XCOePozN53SgjqrWaiONTukgWa\r\n8k/1ZdMWcWttXDRnFvwoiMD7leDXYzy0rASrN1idPj+In0qA" +
            "fHWiZmSRE/tJLR1R\r\nOGbbZtaBmug9oPDsAZjMoTQg+A457OEH+8T75u4HKFccrDHgQ/tpMAOg2M7hyD" +
            "iJ\r\nFuAxaTPXU6xdEl7G9d+wqAuunu6S2tmPHkKcgfWWuFmMND9Dm8EMABt7kAlZoc2p\r\neJVvHeRQY8" +
            "pdx4QUq0tNg0Tx7TTpAlEBAoIBAB4S0umMpi5VB8L4H6qTrLW+Ae1H\r\nVYy+0uEsbn+AlIsedRPMBSwk" +
            "yT9aMH9TSg7aC2aF4GwnuSiGzO/UItI4jegBnDvd\r\nK3dtc92lj2l2ykCsAkTO7OXwfR+d2OK2GBjWmR" +
            "RRkKBnb6Umb2cGZvHfvaVxceaA\r\nauOEK1doyI+G/9gGFCc1c0k2p31NHnIyFaNIkJkLESOjytxlhnfU" +
            "O0UtC/oUKJeO\r\nXzW/0y2UKuXao5fuS6pjsP9DEZaSQCmcG6U6iWvYx0v2v02OT72VW6V6G+JUL9xK\r\n" +
            "gLF24CuAaz9Y3AAkj21UR7AqeyqEjC/TNPbgJrUX0Feg/nInP5FE+LMez6g=\r\n-----END RSA PRIVA" +
            "TE KEY-----\r\n")]
        public string PrivateCert {
            get {
                return ((string)(this["PrivateCert"]));
            }
            set {
                this["PrivateCert"] = value;
            }
        }
    }
}
