//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotSpiderAgentService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-----BEGIN RSA PRIVATE KEY-----\r\nMIIJKQIBAAKCAgEA7W6R3ZqiIsfOiyRLqRnTP7rMm3TirPOE" +
            "aJeCUJ5spGhI8g1/\r\n4pdDVcABARmaP/m/uNHIXePVjHGwMRAgVqU6Xn6RUzCRBc/My4GN4ww8z4B0pF" +
            "qC\r\nHoTFYR1RaaeAjbdQRM40Khevp986BbGQdzqunmlvIm7bW2w9wT9iBHErqxTfO3j5\r\nGewDACgY5H" +
            "WS9WFfMKDDiqVHkxrZgQa2vlCnjT21dc2CbGSynncois1kszgaF8xw\r\nKgNOj+DzrO89AASKyDm4DEln" +
            "cEa4r5F7LzoxtObZU37EIb105lxE+GCUseYjMf5D\r\n/WVIoTt/FtEBYRTEBlG7cOQimxlJhNUYZTcqF4" +
            "dzoKW8X09R0GYjWHZh+/8Q2mj+\r\nQqRrbgNuLR3sKp52nueakfec5fGyN9uUlLK/D8q+JjWERgILXWrM" +
            "pHWoklEXKniM\r\nlFNMTHA52t4nlsEzdx3EFNeXCdmkHloXlnLsaH0BTyQu67LVezKGfG3ZNTtfjJ55\r\n" +
            "yIFJm6oUo0yqo6qXgAPQrccIf7ETTTt4dLERsorqfWq+eHb1EB3MlYbtiLjodQ46\r\nTmTO+YMC7P2aiw" +
            "T7xoO9KBcSqsIxJ1osy7n+dslV4adv3YnMY9ZirNHTmKtuX5QO\r\nCDMa8I7QxmZoHHVeetq9plSM4daK" +
            "AAJCwomAdSmMxi9tMl/r5qZZ28+VmGcCAwEA\r\nAQKCAgEAopkTGZC5MlplDxLHIcIG0mEJl/h+93Q5HC" +
            "uN2cn0ms60DdfC2Zk/Sq0X\r\nwvoWkXNmoZpAvlO1vd1pjN//VXcHtwi0WyUqW7GIDWHmmjOaPXw55Qf6" +
            "jg3c4fni\r\n9Bj6x5JfTQ9t19mquKr9oEKOragpR2Dq88i5Pi2tSPcwF9yszBeaHK9m4CKpl2Te\r\nTy5Z" +
            "euO4/aNK5lrz3kEH7P19Dm5LoEU/TLJ1e+emDzGJOS0ZpkZoUB34Pj1PgubJ\r\n2Ydo3ec+Z4pniTqHtP" +
            "MprUpS8u/GdJ2W/UAV7wlA0jUkInh5vC7fsW/wfcrr50bI\r\nbQarDCHdcHpuhAwnytGRcH9CmqYhkvOx" +
            "2xpYWlrqG+ZFg2ypd5r7PP+A4mBwbQbv\r\nZ3iDWRP+uM20I9NM2qiig9qk1abG2rVan8Ifkr3bn/SdYW" +
            "/Qf5Y1RIw3vohxgz3H\r\nspuYvL9sItuBKpZ5oNJ6nBvA/WBk7aAO2PgkLVst+eLgGzp2zx/ILs8syw4g" +
            "Lf6x\r\nCA87UTqG4K8BnBrVjp27XNj7wL4smCtMtd5qkZtmCPrqlAIDPzklPe0wzJpnAxqT\r\n06avnqtB" +
            "LuPWJqmc9PaE9XB/gL4OrbUKfxOAbLeiPnhsBV1JBZ33HQRNqS6Krr5a\r\nqu4FQl5VKkZpYpqCg+x835" +
            "CSidCiYObbpG7GYvVppN6KnqyvzRkCggEBAPxgXv28\r\nlqzVSVAg57oYo1ec1p+18utytw1hIziM54x1" +
            "NcVtsFUnQ4hq/gCdXUwch86S03sy\r\nIGdSMaseRg8lLHoTzXS77MDjN3prwslktAzOpVEJgmEkSoyXse" +
            "o0AkrFfcCONWuA\r\n1okKw9gqqkNX3qtkdyp4QlAxiFCQUFC5RVXX4pPRCBWU8U/RlVt76qx5hdaay0Fc" +
            "\r\n1oeJQ/VkYRFlGRd7NsVNpxlXsVKSnb2BByxFl+dYi7sufxgYRdmgElZzRjgFYNzO\r\nymLQNS1zJKuR" +
            "Nl0K3steBurr6oB5X4w8BbEyySlboByYnGZvTua6bF9Lz0mebKK/\r\niU7Wgcke5S7ZIAMCggEBAPDXRN" +
            "ltW9dgcT++PtMhrHROeiDINlf+ZKgNZsHTdEm3\r\npHDj9XKcV4D+jfoDodyxXU0Poquhmp/n+RoQeg7S" +
            "HbWJj+WzvhiIjuXlo0pjV5EW\r\nPubTB70InhGq7wKlW+tPzBVDcwdQa6xh5k8U+5RO2VKXx6v21Wi02T" +
            "0DlMoVD7Js\r\nmpeFEAHJvw/JeDGeScqoQgPWN6x/AI8CRZcJwkvjBP4YtcN1b5mc0SNjbzTyZSjt\r\nbg" +
            "/RgKIe6w772oSTuLlXKM/ULzDEcxk10Iph5Fo4ZZvffBZSB3+GP0cvUvPuJylu\r\nJctCEJmz1jF8ucff" +
            "Lt0O7iMTOuNnEFmGuvbvcn/SUs0CggEBAKzyocYCKcNQ+keV\r\n9Ra7cZxFl3KlLk4ZM8ZQbeF/9eF0JS" +
            "Ahdfg0yvu+Tkg/jsLsvkhap+BBzqDfW7gn\r\nK92PHPafgWlgqvLYApm7JSX8A8LPDc0F1joZs5i7D6ou" +
            "b++rfOyqx4LfLKWHIgSN\r\n4FX77lTHqT4KYW8xMnf7HX7kJ9aW9edUFNUtV1zahB7IQV5mfMg/FdC5/S" +
            "2ubErK\r\nuhZAkLxdrH/zIfKk/JhYbw6BUFgPbPSV4lOonmH1qFBleIuTvWgAj4thjqG+iuKV\r\niGimP3" +
            "ntTBZTXiw49V+LTWX9b+0pn17fMk7Gak9sMca9tCxt+CQ8E7hHx6GmMBSS\r\nPn4nPt8CggEAVTw6d6DG" +
            "cjEFo4OXBG3UdM0ZV+TDpty3juo/RbWqYDSIFBP5V/iQ\r\n12w/nw4OCOcUmCNCdO+ao6Ebfef66qfeL9" +
            "Nhg+/bBR+/QwnEgp0p7oUq+dIR2Qrl\r\ntmcCc7NGFr+FALmASkRh9v4m3jIU32YQb7Sby/ZtjMMEZx2P" +
            "WP2fMoxRIfLLuXZH\r\nEjVBPn5Aq2JlCqqTxY6lCffJ3SxtASJ1L+Ba47P6LSlcsuOMBfcLajKtUxfYKI" +
            "g8\r\ntG7Z5TXKmH2KShNUKDQ+b9ul1HPUt0FiZInxhoy9bpp6Zp0PBJlybq023vqgmWUW\r\nFymHLn+EPG" +
            "P+T5eMrdJZ7PVL0fzoTuiGuQKCAQBDkdFHLlySBIc+wNzWilhqbP0K\r\n4FW5wTc8+TAzbE79mw75rMRX" +
            "lLSb6DR6pIg7n+AABC553dEivGkolRDeliwB68qo\r\nQIit7EpJsaaN+GVNr3CUFulYoAtn2WSzsmEfAf" +
            "CUcAVXHjXM7SGjmsZ/Kjsr+gKB\r\nu5HMrMClhxyzkch57YH0ga9mIE6gKE8g/fFyFpN0sKr7XTiAO7dK" +
            "NEM4fLuUmhpr\r\nxwdci/2Sj4wn4RW8I5lOixjp01YBSzF9h51Ydd0mGw3vMWlmZgTTuuyZUbFeo3c6\r\n" +
            "7MniJOkejhSE2XqpgtB/w6lce2MX47W9DIbkOUfisPq/1zsV4Nredj3s16Mx\r\n-----END RSA PRIVA" +
            "TE KEY-----\r\n")]
        public string PrivateCert {
            get {
                return ((string)(this["PrivateCert"]));
            }
            set {
                this["PrivateCert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA7W6R3ZqiIsfOiyRLqRnT
P7rMm3TirPOEaJeCUJ5spGhI8g1/4pdDVcABARmaP/m/uNHIXePVjHGwMRAgVqU6
Xn6RUzCRBc/My4GN4ww8z4B0pFqCHoTFYR1RaaeAjbdQRM40Khevp986BbGQdzqu
nmlvIm7bW2w9wT9iBHErqxTfO3j5GewDACgY5HWS9WFfMKDDiqVHkxrZgQa2vlCn
jT21dc2CbGSynncois1kszgaF8xwKgNOj+DzrO89AASKyDm4DElncEa4r5F7Lzox
tObZU37EIb105lxE+GCUseYjMf5D/WVIoTt/FtEBYRTEBlG7cOQimxlJhNUYZTcq
F4dzoKW8X09R0GYjWHZh+/8Q2mj+QqRrbgNuLR3sKp52nueakfec5fGyN9uUlLK/
D8q+JjWERgILXWrMpHWoklEXKniMlFNMTHA52t4nlsEzdx3EFNeXCdmkHloXlnLs
aH0BTyQu67LVezKGfG3ZNTtfjJ55yIFJm6oUo0yqo6qXgAPQrccIf7ETTTt4dLER
sorqfWq+eHb1EB3MlYbtiLjodQ46TmTO+YMC7P2aiwT7xoO9KBcSqsIxJ1osy7n+
dslV4adv3YnMY9ZirNHTmKtuX5QOCDMa8I7QxmZoHHVeetq9plSM4daKAAJCwomA
dSmMxi9tMl/r5qZZ28+VmGcCAwEAAQ==
-----END PUBLIC KEY-----")]
        public string PublicCert {
            get {
                return ((string)(this["PublicCert"]));
            }
            set {
                this["PublicCert"] = value;
            }
        }
    }
}
