//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBotSpiderAgent.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAysRsFi3LipnQvW6XQ3pv
LIPiEEKcUfvQROAsW/PxCTHuTyITxoDwocPNqMseBVTLsH3ym7Biu7Z2RjpBX6Ko
0gRfOxr8tH/Q1SAcacroM7loBEYUiVn8Ek/7oS5BDdjp991JpDLwjfpWm6SCw5is
drqNsHJ820gMvF9o2UDxRTNYc0OJ5kPqiNUhw6rnSr9ZaYbJuFC0pMxFeSF1C6KD
PVRnZZCLbjVP7hHBAQ8DUpAagLY6Dy9AK5Dsxfx7jTXA0X+RP1SfWfSJ+YtSxsV6
+1g3XIrlcAp+Cd1oXFNYK+fFUDmyjO94wV/JvzV8ylLvBU8zi6P574OTsZLwkQdp
EQIDAQAB
-----END PUBLIC KEY-----
")]
        public string PublicKey {
            get {
                return ((string)(this["PublicKey"]));
            }
            set {
                this["PublicKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-----BEGIN RSA PRIVATE KEY-----\r\nMIIEpQIBAAKCAQEAysRsFi3LipnQvW6XQ3pvLIPiEEKcUfvQ" +
            "ROAsW/PxCTHuTyIT\r\nxoDwocPNqMseBVTLsH3ym7Biu7Z2RjpBX6Ko0gRfOxr8tH/Q1SAcacroM7loBE" +
            "YU\r\niVn8Ek/7oS5BDdjp991JpDLwjfpWm6SCw5isdrqNsHJ820gMvF9o2UDxRTNYc0OJ\r\n5kPqiNUhw6" +
            "rnSr9ZaYbJuFC0pMxFeSF1C6KDPVRnZZCLbjVP7hHBAQ8DUpAagLY6\r\nDy9AK5Dsxfx7jTXA0X+RP1Sf" +
            "WfSJ+YtSxsV6+1g3XIrlcAp+Cd1oXFNYK+fFUDmy\r\njO94wV/JvzV8ylLvBU8zi6P574OTsZLwkQdpEQ" +
            "IDAQABAoIBAHkwgPGYmWjTmiE+\r\ncgYQrVXL1VemmEuf19Dys1CaMlwujaKaWXtxIWFt6AOUsvK4xa1M" +
            "+a339GsBGRvM\r\nQbppO8Gaf1iSPqubITPgp1rLvZD8paC4Shn1wGUpjNm/DX67QMu2ZQdQstoI367S\r\n" +
            "2p0RKTMlOP5Wzy04mPQVilMfL5UNlNwXWbsZHCkoeL8UEiGbZDsA3gB3eQzJFMjG\r\ndiPkQrfuUBIJe3" +
            "jF4kq7hTq9x+Vnt99zR4kspkdQJguxEOs6v5k8d3IZ6si7d1uZ\r\nvpFb3gmntqcyfZg5z6azsgmpOL6e" +
            "uokQ3MqLcpRWM4i3bH+n5lRIrbrBZMR+zvCU\r\nFnJRUGkCgYEA5RtazmAo+9fQkbVfq98lZ3h0Nbe6hB" +
            "d5j6PPR4VgRoYXMxOMGiso\r\nsJtE5Jso+Gd0OErzGIEEYjER1HB6YISWaxzx8CK4eBm3R6dThbBxIuFq" +
            "dpFVlazg\r\njrCzTCX+JhMxaTAOPkqDRxB2+h8yUkbQIicCfvis3T5N9+/iSfrW2JMCgYEA4pGQ\r\nntsQ" +
            "DIStE955VulFcM72aogZevBPhhJrvTorIuYbE0zYFPbcgA2ThIgSwVHTPQwi\r\nyv6k51Z2fD0LcOWKmT" +
            "Ev3W6IEfQjEFEWLkpttM44x6nNxOpDhCJ9567kwRwgm7tK\r\nOYjIkv6jj33Z2mFJsTIDpnKh/s/nRrgd" +
            "fPcZ8ksCgYEAhjkHcx7dA+aFF8hVu4Cp\r\nDjyAgLQZ/qcuHZwPpMwcAlUupErQashcN1NQAkpwr08UxK" +
            "IMV4/GfKxY0MfwujkT\r\nUr+Lcm80+Y+/U6hRA2LCdXfwgnRU2rKEgLQ+5t7fTXkzGnf/8DiBPpID0jeS" +
            "qKc5\r\n6rhF+xM/WwLUdOxB+6uMUScCgYEAhZDAzBViaa7RhbQSnjzYlf88X2MqekIu71/u\r\nqdgf0+wJ" +
            "LCCSBhHdvZPDUk8Rl2vQdt2vqTHjLwnWwbkPBJgdU+AeUpC1oLfm79iN\r\nle6ErCEicfpVdu+Pq9bVmH" +
            "6PFpSpWIVZ5X8Qly+MZqwPgOD3m4Fbi4VqoJgZxKQH\r\npkLZxe8CgYEAyszARcE/b4MHm6mqc5/beD7U" +
            "caij6m1r3pgGTCQVOwoeaec/gXHl\r\no8WwgfizTkbhwp7iIkto334zMrEbLP8KrzNJFqY53L0Su2Xagg" +
            "3uyibfGzq3Yfn3\r\nt2n9l172lb2NiwRPhJ64/bJfD/0G33cM3TP4/o6R/bFi2wmGyFpWpDw=\r\n-----E" +
            "ND RSA PRIVATE KEY-----\r\n")]
        public string PrivateKey {
            get {
                return ((string)(this["PrivateKey"]));
            }
            set {
                this["PrivateKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnonwIlmu9odehkSOYwum
inlssW1VMh/IEm+qutzBaRTKQbK8HxnY18ltFoJJCoqivXPZWwPI2wQxMamkY/yz
1JcVGmb50d6t0FK14l1rNatrAvVXtcl7tG/tH5vh/8VIsGZIQ991SfiAqzPEl97m
SHpGpB/wb4JZop4JEk81j4qmE3l1Qdx7zXbdwBBz1qSt7dhL744y1OzMX6/1GE7l
+bK4tj8CCN8QPdVkc9ZRNQ0L0Ltrx8eqkDblcR33r32XN/VyL/sRoCRVZYO4qUKr
Xmo/qipkJUbNWTH3YseTdNYDIN+IGKnQJmaipZy2E8pZmPPM7PjT7P0nMNbeKL3u
SQIDAQAB
-----END PUBLIC KEY-----")]
        public string OtherPublicKey {
            get {
                return ((string)(this["OtherPublicKey"]));
            }
            set {
                this["OtherPublicKey"] = value;
            }
        }
    }
}
